import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { ProviderComponent } from "../app/providerComponent";
import NavebarProvider from "@/components/header/navebarProvider";
import Section8Provider from "@/components/body/section8/section8Provider";
import FooterProvider from "@/components/footer/footerProvider";

export const metadata: Metadata = {
  title: "All Walks",
  description: "Generated by create next app",
};
<link
  href="https://db.onlinewebfonts.com/c/cf9209cb40da7169670815cd8c1860c9?family=Self+Modern+Regular"
  rel="stylesheet"
></link>;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <ProviderComponent>
          <NextTopLoader
            color="#000000"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #000000,0 0 5px #000000"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
          <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />
          <NavebarProvider />
          {children}
          <Section8Provider />
          <FooterProvider />
        </ProviderComponent>
      </body>
    </html>
  );
}
